In [52]:
import numpy as np 
import pandas as pd

In [53]:
df = pd.read_csv('cars.csv')

In [54]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [55]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# One Hot Encoding using Pandas
### But it is not recommendated to used in Ml Model 
### Because it always give different values on each execution

In [56]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# K-1 One Hot Encoding

Drop parameter drop first dummy variable to avoid multiconlinearity

In [57]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# Train Test Split

In [58]:
x = df.iloc[:,0:4]
x

        brand  km_driven    fuel                 owner
0      Maruti     145500  Diesel           First Owner
1       Skoda     120000  Diesel          Second Owner
2       Honda     140000  Petrol           Third Owner
3     Hyundai     127000  Diesel           First Owner
4      Maruti     120000  Petrol           First Owner
...       ...        ...     ...                   ...
8123  Hyundai     110000  Petrol           First Owner
8124  Hyundai     119000  Diesel  Fourth & Above Owner
8125   Maruti     120000  Diesel           First Owner
8126     Tata      25000  Diesel           First Owner
8127     Tata      25000  Diesel           First Owner

[8128 rows x 4 columns]

In [59]:
y = df.iloc[:,-1]
y

0       450000
1       370000
2       158000
3       225000
4       130000
         ...
8123    320000
8124    135000
8125    382000
8126    290000
8127    290000
Name: selling_price, Length: 8128, dtype: int64

In [60]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2,random_state=0)

# One Hot Encoding

In [61]:
from sklearn.preprocessing import OneHotEncoder

Sparsity parameter used to avoid sparse matrix and at the end .toarray require to display result

dtypes parameter convert float ponit to int

In [62]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [63]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']])
x_test_new = ohe.transform(x_test[['fuel','owner']])

In [64]:
x_train_new.shape

(6502, 7)

To concatenate One hot encoder columns and remaining columns

In [68]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))
np.hstack((x_test[['brand','km_driven']].values,x_test_new))

array([['Hyundai', 40000, 1, ..., 0, 0, 0],
       ['Mahindra', 70000, 1, ..., 0, 0, 0],
       ['Maruti', 5000, 0, ..., 0, 0, 0],
       ...,
       ['Maruti', 40000, 1, ..., 0, 0, 0],
       ['Hyundai', 2350, 0, ..., 0, 0, 0],
       ['Hyundai', 80000, 1, ..., 1, 0, 0]], dtype=object)

# OneHOt Encoding With top Categories

In [73]:
counts = df['brand'].value_counts()

In [75]:
df['brand'].nunique()
threshold=100

In [76]:
repl = counts[counts<=threshold].index

In [79]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
7665,False,False,False,False,False,False,False,False,True,False,False,False,False
3990,False,False,False,False,False,False,True,False,False,False,False,False,False
1033,False,False,False,True,False,False,False,False,False,False,False,False,False
5535,False,False,False,False,True,False,False,False,False,False,False,False,False
3902,False,False,True,False,False,False,False,False,False,False,False,False,False