In [17]:
import numpy as np
import pandas as pd

In [18]:
df = pd.read_csv('ecommerce_dataset_10000.csv',usecols=[1,2,9,10,11,14,16,17])

In [19]:
df.head()

,first_name,last_name,category,quantity,unit_price,order_status,rating,review_text
0,Erica,Oliver,Electronics,3,229,Pending,2,good
1,Christopher,White,Apparel,4,59,Pending,2,average
2,Spencer,Foster,Toys,2,59,Delivered,5,good
3,Jessica,Harris,Home & Kitchen,4,399,Delivered,2,very good
4,Amy,Johnson,Apparel,1,110,Returned,1,very good

# Feature Construction

In [20]:
df['Full_Name'] = df['first_name'] + " " + df['last_name']

In [21]:
df.drop(columns=['first_name','last_name'],inplace=True)

In [23]:
df['order_status'].value_counts()

order_status
Shipped      2063
Delivered    2037
Cancelled    1970
Pending      1968
Returned     1962
Name: count, dtype: int64

In [22]:
df.head()

,category,quantity,unit_price,order_status,rating,review_text,Full_Name
0,Electronics,3,229,Pending,2,good,Erica Oliver
1,Apparel,4,59,Pending,2,average,Christopher White
2,Toys,2,59,Delivered,5,good,Spencer Foster
3,Home & Kitchen,4,399,Delivered,2,very good,Jessica Harris
4,Apparel,1,110,Returned,1,very good,Amy Johnson

# Feature Splitting

In [24]:
df['order_completion'] = df['order_status']
df['order_completion'].loc[df['order_status']=='Delivered'] = "Completed"
df['order_completion'].loc[df['order_status']!='Delivered'] = "Not Completed"

C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_5780\3840721570.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['order_completion'].loc[df['order_status']=='Delivered'] = "Completed"
C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_5780\3840721570.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_completion'].loc[df['order_status']=='Delivered'] = "Completed"
C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_5780\3840721570.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['order_completion'].loc[df['order_status']!='Delivered'] = "Not Completed"
C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_5780\3840721570.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_completion'].loc[df['order_status']!='Delivered'] = "Not Completed"

In [25]:
df.head()

,category,quantity,unit_price,order_status,rating,review_text,Full_Name,order_completion
0,Electronics,3,229,Pending,2,good,Erica Oliver,Not Completed
1,Apparel,4,59,Pending,2,average,Christopher White,Not Completed
2,Toys,2,59,Delivered,5,good,Spencer Foster,Completed
3,Home & Kitchen,4,399,Delivered,2,very good,Jessica Harris,Completed
4,Apparel,1,110,Returned,1,very good,Amy Johnson,Not Completed