In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [5]:
df = pd.read_csv('ecommerce_dataset_10000.csv',usecols=['quantity','unit_price','rating'])

In [6]:
df.head()

   quantity  unit_price  rating
0         3         229       2
1         4          59       2
2         2          59       5
3         4         399       2
4         1         110       1

In [38]:
x = df.iloc[:,[0,1]]
y = df.iloc[:,-1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
y_train.head()

9254    3
1561    2
1670    5
6087    5
6669    4
Name: rating, dtype: int64

In [ ]:
# Without Binarization

In [13]:
clf = DecisionTreeClassifier()

clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

accuracy_score(y_test,y_pred)

0.208

In [15]:
np.mean(cross_val_score(clf,x,y,scoring='accuracy'))

0.1989

In [ ]:
# Applying Binarization

In [30]:
y_train = pd.DataFrame(y_train,columns=['rating'])
y_test = pd.DataFrame(y_test,columns=['rating'])
y_train.head()

      rating
9254       3
1561       2
1670       5
6087       5
6669       4

In [33]:
from sklearn.preprocessing import Binarizer

trf = ColumnTransformer([
    ('trf',Binarizer(copy=False,threshold=2),['rating'])
],remainder='passthrough')

y_train_trf = trf.fit_transform(y_train)
y_test_trf = trf.transform(y_test)

pd.DataFrame(y_train_trf,columns=['rating']).head()

   rating
0       1
1       0
2       1
3       1
4       1

In [ ]:
# With Binarization

In [35]:
clf = DecisionTreeClassifier()

clf.fit(x_train,y_train_trf)

y_pred2 = clf.predict(x_test)

accuracy_score(y_test,y_pred2)

0.1965

In [40]:
y = pd.DataFrame(y,columns=['rating'])
y_trf = trf.transform(y)
np.mean(cross_val_score(clf,x,y_trf,scoring='accuracy'))

0.5949