In [42]:
import  numpy as np 
import pandas as pd

In [43]:
df = pd.read_csv('used_car_listings.csv',usecols=['mileage','price','condition','location','features'])

In [44]:
df.head()

,mileage,price,condition,location,features
0,46134,19919.0,good,"New Lindsey, GA, US","Alloy Wheels, Android Auto, Apple CarPlay, Fog..."
1,16109,19480.0,good,"Pughtown, CO, US","Alloy Wheels, Android Auto, Lane Keep Assist, ..."
2,173239,4556.0,good,"Satna, HR, India","Alloy Wheels, Bluetooth, Panoramic Roof, Sunroof"
3,36810,11536.0,fair,"山武市, Osaka, Japan","Alloy Wheels, Bluetooth, Keyless Entry, Naviga..."
4,87749,14098.0,good,"長生郡長生村, Osaka, Japan","Apple CarPlay, Backup Camera, Bluetooth, Heate..."

In [45]:
df[['City','Province','Country']] = df['location'].str.split(',',expand=True)

In [46]:
df.shape

(2068, 8)

In [47]:
df['features'] = df['features'].fillna('unknown')

In [48]:
df.head()

,mileage,price,condition,location,features,City,Province,Country
0,46134,19919.0,good,"New Lindsey, GA, US","Alloy Wheels, Android Auto, Apple CarPlay, Fog...",New Lindsey,GA,US
1,16109,19480.0,good,"Pughtown, CO, US","Alloy Wheels, Android Auto, Lane Keep Assist, ...",Pughtown,CO,US
2,173239,4556.0,good,"Satna, HR, India","Alloy Wheels, Bluetooth, Panoramic Roof, Sunroof",Satna,HR,India
3,36810,11536.0,fair,"山武市, Osaka, Japan","Alloy Wheels, Bluetooth, Keyless Entry, Naviga...",山武市,Osaka,Japan
4,87749,14098.0,good,"長生郡長生村, Osaka, Japan","Apple CarPlay, Backup Camera, Bluetooth, Heate...",長生郡長生村,Osaka,Japan

In [49]:
df['features'].unique()

array(['Alloy Wheels, Android Auto, Apple CarPlay, Fog Lights, LED Headlights, Parking Sensors, Ventilated Seats',
       'Alloy Wheels, Android Auto, Lane Keep Assist, Navigation, Panoramic Roof, Parking Sensors, Push Button Start, Wireless Charging',
       'Alloy Wheels, Bluetooth, Panoramic Roof, Sunroof', ...,
       'Adaptive Cruise Control, Android Auto, Blind Spot Monitor, Navigation, Wireless Charging',
       'Backup Camera, Panoramic Roof, Parking Sensors, Push Button Start',
       'Adaptive Cruise Control, Android Auto, Apple CarPlay, Bluetooth, Fog Lights, Heated Seats, LED Headlights'],
      dtype=object)

In [50]:
df['features'].isnull().sum()

0

In [51]:
df.shape

(2068, 8)

In [52]:
features_split = df['features'].str.split(',',expand=True)

In [53]:
unique_features = set(df['features'].str.split(',').explode().str.strip())

In [54]:
for feature in unique_features:
    df[feature.strip()] = df['features'].apply(lambda x: feature.strip() in [f.strip() for f in x.split(',')])

In [55]:
df.head()

,mileage,price,condition,location,features,City,Province,Country,Leather Seats,Keyless Entry,...,Apple CarPlay,Blind Spot Monitor,Backup Camera,Sunroof,Fog Lights,Heated Seats,Android Auto,LED Headlights,Parking Sensors,Wireless Charging
0,46134,19919.0,good,"New Lindsey, GA, US","Alloy Wheels, Android Auto, Apple CarPlay, Fog...",New Lindsey,GA,US,False,False,...,True,False,False,False,True,False,True,True,True,False
1,16109,19480.0,good,"Pughtown, CO, US","Alloy Wheels, Android Auto, Lane Keep Assist, ...",Pughtown,CO,US,False,False,...,False,False,False,False,False,False,True,False,True,True
2,173239,4556.0,good,"Satna, HR, India","Alloy Wheels, Bluetooth, Panoramic Roof, Sunroof",Satna,HR,India,False,False,...,False,False,False,True,False,False,False,False,False,False
3,36810,11536.0,fair,"山武市, Osaka, Japan","Alloy Wheels, Bluetooth, Keyless Entry, Naviga...",山武市,Osaka,Japan,False,True,...,False,False,False,True,False,False,False,False,False,True
4,87749,14098.0,good,"長生郡長生村, Osaka, Japan","Apple CarPlay, Backup Camera, Bluetooth, Heate...",長生郡長生村,Osaka,Japan,False,False,...,True,False,True,False,False,True,False,False,False,True

In [56]:
df.shape

(2068, 29)