In [53]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [54]:
df = pd.read_csv('used_car_listings.csv',usecols=['trim','mileage','price','condition'])

In [55]:
df.head()

    trim  mileage    price condition
0    NaN    46134  19919.0      good
1     LT    16109  19480.0      good
2    XLE   173239   4556.0      good
3     EX    36810  11536.0      fair
4  Trend    87749  14098.0      good

In [46]:
mi = MissingIndicator()

mi.fit(df)

df_missing = mi.transform(df)

In [47]:
df_missing

array([[ True, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [48]:
df['experience_na'] = df_missing[:,0] 

df['training_hours_na'] = df_missing[:,-1]

In [49]:
df.head()

    trim  mileage    price condition  experience_na  training_hours_na
0    NaN    46134  19919.0      good           True              False
1     LT    16109  19480.0      good          False              False
2    XLE   173239   4556.0      good          False              False
3     EX    36810  11536.0      fair          False              False
4  Trend    87749  14098.0      good          False              False

In [56]:
si = SimpleImputer(add_indicator=True,strategy='most_frequent')

si.fit(df)

SimpleImputer(add_indicator=True, strategy='most_frequent')

In [57]:
df = si.transform(df)

In [58]:
df

array([['Touring', 46134, 19919.0, 'good', True, False],
       ['LT', 16109, 19480.0, 'good', False, False],
       ['XLE', 173239, 4556.0, 'good', False, False],
       ...,
       ['EX', 120452, 7093.0, 'good', False, False],
       ['LX', 57043, 11296.0, 'excellent', False, False],
       ['Platinum', 20218, 23558.0, 'excellent', False, False]],
      dtype=object)