In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('loan_approval.csv')

In [3]:
df.head()

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

   income  credit_score  loan_amount  years_employed  points  loan_approved
0  113810           389        39698              27    50.0          False
1   44592           729        15446              28    55.0          False
2   33278           584        11189              13    45.0          False
3  127196           344        48823              29    50.0          False
4   66048           496        47174               4    25.0          False

In [6]:
x = df.iloc[:,:-1]
y = df['loan_approved']

In [7]:
x

      income  credit_score  loan_amount  years_employed  points
0     113810           389        39698              27    50.0
1      44592           729        15446              28    55.0
2      33278           584        11189              13    45.0
3     127196           344        48823              29    50.0
4      66048           496        47174               4    25.0
...      ...           ...          ...             ...     ...
1995   92163           770        12251              13    85.0
1996   38799           635        48259              17    40.0
1997   41957           763        16752               5    60.0
1998  139022           360        24031              35    55.0
1999   41188           482        31397               6    20.0

[2000 rows x 5 columns]

In [8]:
y

0       False
1       False
2       False
3       False
4       False
        ...
1995     True
1996    False
1997     True
1998    False
1999    False
Name: loan_approved, Length: 2000, dtype: bool

# TrainTest Split

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_train = train_test_split(x, y, test_size=0.3, random_state=0)

# MInMaxScaler

In [12]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(x_train)

x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [14]:
x_train_scaled  = pd.DataFrame(x_train_scaled, columns=x_train.columns)
x_test_scaled  = pd.DataFrame(x_test_scaled, columns=x_test.columns)

In [15]:
np.round(x_train.describe(),1)

         income  credit_score  loan_amount  years_employed  points
count    1400.0        1400.0       1400.0          1400.0  1400.0
mean    90321.2         574.7      25417.5            20.9    56.8
std     34758.3         160.6      14200.0            11.8    18.5
min     30053.0         300.0       1022.0             0.0    10.0
25%     60479.5         433.0      12930.8            10.0    45.0
50%     90052.0         582.5      25748.5            21.0    55.0
75%    120099.8         714.2      37530.8            31.0    70.0
max    149806.0         850.0      49999.0            40.0   100.0

In [16]:
np.round(x_train_scaled.describe(),1)

       income  credit_score  loan_amount  years_employed  points
count  1400.0        1400.0       1400.0          1400.0  1400.0
mean      0.5           0.5          0.5             0.5     0.5
std       0.3           0.3          0.3             0.3     0.2
min       0.0           0.0          0.0             0.0     0.0
25%       0.3           0.2          0.2             0.2     0.4
50%       0.5           0.5          0.5             0.5     0.5
75%       0.8           0.8          0.7             0.8     0.7
max       1.0           1.0          1.0             1.0     1.0