In [24]:
import numpy as np
import pandas as pd
import seaborn as sns

In [25]:
df = sns.load_dataset('iris')

In [26]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [27]:
df = df.iloc[:,1:]

In [28]:
df.head()

   sepal_width  petal_length  petal_width species
0          3.5           1.4          0.2  setosa
1          3.0           1.4          0.2  setosa
2          3.2           1.3          0.2  setosa
3          3.1           1.5          0.2  setosa
4          3.6           1.4          0.2  setosa

In [29]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [30]:
df.head()

   sepal_width  petal_length  petal_width  species
0          3.5           1.4          0.2        0
1          3.0           1.4          0.2        0
2          3.2           1.3          0.2        0
3          3.1           1.5          0.2        0
4          3.6           1.4          0.2        0

In [31]:
df = df[df['species'] != 0][['sepal_width','petal_length','species']]

In [32]:
df.head()

    sepal_width  petal_length  species
50          3.2           4.7        1
51          3.2           4.5        1
52          3.1           4.9        1
53          2.3           4.0        1
54          2.8           4.6        1

In [33]:
# Taking only 10 rows for training
df = df.sample(100)
df_train = df.iloc[:60,:].sample(10)
df_val = df.iloc[60:80,:].sample(5)
df_test = df.iloc[80:,:].sample(5)

In [34]:
X_test = df_val.iloc[:,0:2].values
y_test = df_val.iloc[:,-1].values

# Bagging

In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [60]:
def evaluate(clf,X,y):
    clf.fit(X,y)
    y_pred = clf.predict(X_test)
    print(accuracy_score(y_test,y_pred))

In [67]:
# Data for Tree 1
df_bag = df_train.sample(8,replace=True)

X = df_bag.iloc[:,0:2]
y = df_bag.iloc[:,-1]

df_bag

     sepal_width  petal_length  species
120          3.2           5.7        2
85           3.4           4.5        1
115          3.2           5.3        2
85           3.4           4.5        1
116          3.0           5.5        2
85           3.4           4.5        1
59           2.7           3.9        1
115          3.2           5.3        2

In [68]:
dt_bag = DecisionTreeClassifier()
evaluate(dt_bag,X,y)

1.0

D:\my\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  .. versionchanged:: 1.6

In [69]:
# Data for Tree 2
df_bag = df_train.sample(8,replace=True)

# Fetch X and y
X = df_bag.iloc[:,0:2]
y = df_bag.iloc[:,-1]

# print df_bag
df_bag

     sepal_width  petal_length  species
116          3.0           5.5        2
115          3.2           5.3        2
115          3.2           5.3        2
97           2.9           4.3        1
85           3.4           4.5        1
59           2.7           3.9        1
97           2.9           4.3        1
54           2.8           4.6        1

In [70]:
dt_bag2 = DecisionTreeClassifier()
evaluate(dt_bag2,X,y)

1.0

D:\my\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  .. versionchanged:: 1.6

In [71]:
# Data for Tree 3
df_bag = df_train.sample(8,replace=True)

# Fetch X and y
X = df_bag.iloc[:,0:2]
y = df_bag.iloc[:,-1]

# print df_bag
df_bag

     sepal_width  petal_length  species
85           3.4           4.5        1
76           2.8           4.8        1
101          2.7           5.1        2
115          3.2           5.3        2
76           2.8           4.8        1
123          2.7           4.9        2
59           2.7           3.9        1
115          3.2           5.3        2

In [72]:
dt_bag3 = DecisionTreeClassifier()
evaluate(dt_bag3,X,y)

1.0

D:\my\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  .. versionchanged:: 1.6

## Predict

In [57]:
df_test

     sepal_width  petal_length  species
73           2.8           4.7        1
98           2.5           3.0        1
82           2.7           3.9        1
144          3.3           5.7        2
69           2.5           3.9        1

In [58]:
print("Predictor 1",dt_bag.predict(np.array([3.3,5.7]).reshape(1,2)))
print("Predictor 2",dt_bag2.predict(np.array([3.3,5.7]).reshape(1,2)))
print("Predictor 3",dt_bag3.predict(np.array([3.3,5.7]).reshape(1,2)))

Predictor 1 [2]
Predictor 2 [2]
Predictor 3 [2]

D:\my\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  .. versionchanged:: 1.6
D:\my\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  .. versionchanged:: 1.6
D:\my\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  .. versionchanged:: 1.6

The Prediction will be 2