In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('public_transport_delays.csv',usecols=['date','time','delayed'])

In [4]:
df.head()

         date      time  delayed
0  2023-01-01  05:00:00        0
1  2023-01-01  05:15:00        1
2  2023-01-01  05:30:00        0
3  2023-01-01  05:45:00        1
4  2023-01-01  06:00:00        1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     2000 non-null   object
 1   time     2000 non-null   object
 2   delayed  2000 non-null   int64
dtypes: int64(1), object(2)
memory usage: 47.0+ KB

In [6]:
# Coverting to datetime datatype
df['date'] = pd.to_datetime(df['date'])
df['time'] = pd.to_datetime(df['time'])

C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_380\2066619367.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['time'] = pd.to_datetime(df['time'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     2000 non-null   datetime64[ns]
 1   time     2000 non-null   datetime64[ns]
 2   delayed  2000 non-null   int64
dtypes: datetime64[ns](2), int64(1)
memory usage: 47.0 KB

In [8]:
# Working With date

In [9]:
df['date_year'] = df['date'].dt.year
df.head()

        date                time  delayed  date_year
0 2023-01-01 2025-10-12 05:00:00        0       2023
1 2023-01-01 2025-10-12 05:15:00        1       2023
2 2023-01-01 2025-10-12 05:30:00        0       2023
3 2023-01-01 2025-10-12 05:45:00        1       2023
4 2023-01-01 2025-10-12 06:00:00        1       2023

In [10]:
df['date_month_num'] = df['date'].dt.month
df.head()

        date                time  delayed  date_year  date_month_num
0 2023-01-01 2025-10-12 05:00:00        0       2023               1
1 2023-01-01 2025-10-12 05:15:00        1       2023               1
2 2023-01-01 2025-10-12 05:30:00        0       2023               1
3 2023-01-01 2025-10-12 05:45:00        1       2023               1
4 2023-01-01 2025-10-12 06:00:00        1       2023               1

In [11]:
df['date_month_name'] = df['date'].dt.month_name()
df.head()

,date,time,delayed,date_year,date_month_num,date_month_name
0,2023-01-01,2025-10-12 05:00:00,0,2023,1,January
1,2023-01-01,2025-10-12 05:15:00,1,2023,1,January
2,2023-01-01,2025-10-12 05:30:00,0,2023,1,January
3,2023-01-01,2025-10-12 05:45:00,1,2023,1,January
4,2023-01-01,2025-10-12 06:00:00,1,2023,1,January

In [12]:
df['date_day'] = df['date'].dt.day
df.head()

,date,time,delayed,date_year,date_month_num,date_month_name,date_day
0,2023-01-01,2025-10-12 05:00:00,0,2023,1,January,1
1,2023-01-01,2025-10-12 05:15:00,1,2023,1,January,1
2,2023-01-01,2025-10-12 05:30:00,0,2023,1,January,1
3,2023-01-01,2025-10-12 05:45:00,1,2023,1,January,1
4,2023-01-01,2025-10-12 06:00:00,1,2023,1,January,1

In [13]:
df['date_day_name'] = df['date'].dt.day_name()
df.head()

,date,time,delayed,date_year,date_month_num,date_month_name,date_day,date_day_name
0,2023-01-01,2025-10-12 05:00:00,0,2023,1,January,1,Sunday
1,2023-01-01,2025-10-12 05:15:00,1,2023,1,January,1,Sunday
2,2023-01-01,2025-10-12 05:30:00,0,2023,1,January,1,Sunday
3,2023-01-01,2025-10-12 05:45:00,1,2023,1,January,1,Sunday
4,2023-01-01,2025-10-12 06:00:00,1,2023,1,January,1,Sunday

In [14]:
df['date_dayofweek'] = df['date'].dt.dayofweek
df.head()

,date,time,delayed,date_year,date_month_num,date_month_name,date_day,date_day_name,date_dayofweek
0,2023-01-01,2025-10-12 05:00:00,0,2023,1,January,1,Sunday,6
1,2023-01-01,2025-10-12 05:15:00,1,2023,1,January,1,Sunday,6
2,2023-01-01,2025-10-12 05:30:00,0,2023,1,January,1,Sunday,6
3,2023-01-01,2025-10-12 05:45:00,1,2023,1,January,1,Sunday,6
4,2023-01-01,2025-10-12 06:00:00,1,2023,1,January,1,Sunday,6

In [15]:
df['date_is_weekened'] = np.where(df['date_dayofweek'].isin(['Saturady','Sunday']),0,1)
df.head()

,date,time,delayed,date_year,date_month_num,date_month_name,date_day,date_day_name,date_dayofweek,date_is_weekened
0,2023-01-01,2025-10-12 05:00:00,0,2023,1,January,1,Sunday,6,1
1,2023-01-01,2025-10-12 05:15:00,1,2023,1,January,1,Sunday,6,1
2,2023-01-01,2025-10-12 05:30:00,0,2023,1,January,1,Sunday,6,1
3,2023-01-01,2025-10-12 05:45:00,1,2023,1,January,1,Sunday,6,1
4,2023-01-01,2025-10-12 06:00:00,1,2023,1,January,1,Sunday,6,1

In [16]:
df['date_week'] = df['date'].dt.isocalendar().week
df.head()

,date,time,delayed,date_year,date_month_num,date_month_name,date_day,date_day_name,date_dayofweek,date_is_weekened,date_week
0,2023-01-01,2025-10-12 05:00:00,0,2023,1,January,1,Sunday,6,1,52
1,2023-01-01,2025-10-12 05:15:00,1,2023,1,January,1,Sunday,6,1,52
2,2023-01-01,2025-10-12 05:30:00,0,2023,1,January,1,Sunday,6,1,52
3,2023-01-01,2025-10-12 05:45:00,1,2023,1,January,1,Sunday,6,1,52
4,2023-01-01,2025-10-12 06:00:00,1,2023,1,January,1,Sunday,6,1,52

In [17]:
df['date_quarter'] = df['date'].dt.quarter
df.head()

,date,time,delayed,date_year,date_month_num,date_month_name,date_day,date_day_name,date_dayofweek,date_is_weekened,date_week,date_quarter
0,2023-01-01,2025-10-12 05:00:00,0,2023,1,January,1,Sunday,6,1,52,1
1,2023-01-01,2025-10-12 05:15:00,1,2023,1,January,1,Sunday,6,1,52,1
2,2023-01-01,2025-10-12 05:30:00,0,2023,1,January,1,Sunday,6,1,52,1
3,2023-01-01,2025-10-12 05:45:00,1,2023,1,January,1,Sunday,6,1,52,1
4,2023-01-01,2025-10-12 06:00:00,1,2023,1,January,1,Sunday,6,1,52,1

In [18]:
df['date_semester'] = np.where(df['date_quarter'].isin([1,2]),1,2)
df.head()

,date,time,delayed,date_year,date_month_num,date_month_name,date_day,date_day_name,date_dayofweek,date_is_weekened,date_week,date_quarter,date_semester
0,2023-01-01,2025-10-12 05:00:00,0,2023,1,January,1,Sunday,6,1,52,1,1
1,2023-01-01,2025-10-12 05:15:00,1,2023,1,January,1,Sunday,6,1,52,1,1
2,2023-01-01,2025-10-12 05:30:00,0,2023,1,January,1,Sunday,6,1,52,1,1
3,2023-01-01,2025-10-12 05:45:00,1,2023,1,January,1,Sunday,6,1,52,1,1
4,2023-01-01,2025-10-12 06:00:00,1,2023,1,January,1,Sunday,6,1,52,1,1

In [19]:
# time elapse between date

In [20]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2025, 10, 12, 4, 9, 16, 296902)

In [21]:
today - df['date']

0      1015 days 04:09:16.296902
1      1015 days 04:09:16.296902
2      1015 days 04:09:16.296902
3      1015 days 04:09:16.296902
4      1015 days 04:09:16.296902
                  ...
1995    995 days 04:09:16.296902
1996    994 days 04:09:16.296902
1997    994 days 04:09:16.296902
1998    994 days 04:09:16.296902
1999    994 days 04:09:16.296902
Name: date, Length: 2000, dtype: timedelta64[ns]

In [22]:
day_passed = (today - df['date']).dt.days
day_passed

0       1015
1       1015
2       1015
3       1015
4       1015
        ...
1995     995
1996     994
1997     994
1998     994
1999     994
Name: date, Length: 2000, dtype: int64

In [23]:
month_passed = ((today.year - df['date'].dt.year) * 12 + today.month - df['date'].dt.month)
month_passed

0       33
1       33
2       33
3       33
4       33
        ..
1995    33
1996    33
1997    33
1998    33
1999    33
Name: date, Length: 2000, dtype: int32

In [24]:
year_passed = (today.year - df['date'].dt.year)
year_passed

0       2
1       2
2       2
3       2
4       2
       ..
1995    2
1996    2
1997    2
1998    2
1999    2
Name: date, Length: 2000, dtype: int32

In [25]:
# Working with Time

In [27]:
df['time_part'] = df['time'].dt.time
df.sample(3)

,date,time,delayed,date_year,date_month_num,date_month_name,date_day,date_day_name,date_dayofweek,date_is_weekened,date_week,date_quarter,date_semester,time_part
1233,2023-01-14,2025-10-12 01:15:00,1,2023,1,January,14,Saturday,5,1,2,1,1,01:15:00
1884,2023-01-20,2025-10-12 20:00:00,1,2023,1,January,20,Friday,4,1,3,1,1,20:00:00
456,2023-01-05,2025-10-12 23:00:00,1,2023,1,January,5,Thursday,3,1,1,1,1,23:00:00

In [28]:
df['hour'] = df['time'].dt.hour
df['minute'] = df['time'].dt.minute
df['second'] = df['time'].dt.second

df.sample(3)

,date,time,delayed,date_year,date_month_num,date_month_name,date_day,date_day_name,date_dayofweek,date_is_weekened,date_week,date_quarter,date_semester,time_part,hour,minute,second
117,2023-01-02,2025-10-12 10:15:00,1,2023,1,January,2,Monday,0,1,1,1,1,10:15:00,10,15,0
1679,2023-01-18,2025-10-12 16:45:00,1,2023,1,January,18,Wednesday,2,1,3,1,1,16:45:00,16,45,0
1785,2023-01-19,2025-10-12 19:15:00,0,2023,1,January,19,Thursday,3,1,3,1,1,19:15:00,19,15,0

In [29]:
# Time Difference

today - df['time']

0      -1 days +23:09:16.296902
1      -1 days +22:54:16.296902
2      -1 days +22:39:16.296902
3      -1 days +22:24:16.296902
4      -1 days +22:09:16.296902
                 ...
1995   -1 days +04:24:16.296902
1996     0 days 04:09:16.296902
1997     0 days 03:54:16.296902
1998     0 days 03:39:16.296902
1999     0 days 03:24:16.296902
Name: time, Length: 2000, dtype: timedelta64[ns]

In [30]:
# In second

(today - df['time'])/np.timedelta64(1,'s')

0       -3043.703098
1       -3943.703098
2       -4843.703098
3       -5743.703098
4       -6643.703098
            ...
1995   -70543.703098
1996    14956.296902
1997    14056.296902
1998    13156.296902
1999    12256.296902
Name: time, Length: 2000, dtype: float64

In [31]:
# In minute

(today - df['time'])/np.timedelta64(1,'m')

0        -50.728385
1        -65.728385
2        -80.728385
3        -95.728385
4       -110.728385
           ...
1995   -1175.728385
1996     249.271615
1997     234.271615
1998     219.271615
1999     204.271615
Name: time, Length: 2000, dtype: float64

In [32]:
# In hour

(today - df['time'])/np.timedelta64(1,'h')

0       -0.845473
1       -1.095473
2       -1.345473
3       -1.595473
4       -1.845473
          ...
1995   -19.595473
1996     4.154527
1997     3.904527
1998     3.654527
1999     3.404527
Name: time, Length: 2000, dtype: float64