In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import cross_val_score

D:\Users\cccc\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [12]:
!pip install --upgrade scikit-learn mlxtend

Requirement already satisfied: scikit-learn in d:\users\cccc\anaconda3\lib\site-packages (1.9.0)
Collecting mlxtend
  Using cached mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: numpy>=1.24.1 in d:\users\cccc\anaconda3\lib\site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in d:\users\cccc\anaconda3\lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in d:\users\cccc\anaconda3\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in d:\users\cccc\anaconda3\lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in d:\users\cccc\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: pandas>=2.3.3 in d:\users\cccc\anaconda3\lib\site-packages (from mlxtend) (3.0.5)
Requirement already satisfied: matplotlib>=3.10.8 in d:\users\cccc\anaconda3\lib\site-packages (from mlxtend) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in d:\users\cccc\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in d:\users\cccc\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.28.2 in d:\users\cccc\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\users\cccc\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in d:\users\cccc\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (24.2)
Requirement already satisfied: pillow>=9 in d:\users\cccc\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=3 in d:\users\cccc\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in d:\users\cccc\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\users\cccc\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in d:\users\cccc\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Using cached mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.25.0

WARNING: Ignoring invalid distribution ~atplotlib (D:\Users\cccc\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (D:\Users\cccc\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (D:\Users\cccc\anaconda3\Lib\site-packages)

In [2]:
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv')

In [3]:
df.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [4]:
df.isnull().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [5]:
df.drop(columns=['type','fixed acidity','volatile acidity'],inplace=True)

In [6]:
df.dropna(inplace=True)

In [7]:
df.isnull().sum()

citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df['quality'], test_size=0.2, random_state=1)

In [9]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [54]:
import numpy as np
from sklearn.metrics import r2_score
model = LogisticRegression()


print("training",np.mean(cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy')))
print("testing",np.mean(cross_val_score(model, X_test, y_test, cv=5, scoring='accuracy')))

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training 0.5321379238447705
testing 0.516991386991387

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

In [22]:
X_train

array([[ 0.21752121,  0.24035722, -0.77660867, ...,  0.44064869,
        -0.61568968,  1.68094926],
       [ 0.28692491, -0.76471144, -0.63192136, ...,  1.24563422,
         1.05693094,  0.42217209],
       [ 1.81380643, -0.27286933,  1.04645149, ...,  0.44064869,
         3.06407569,  1.26135687],
       ...,
       [ 0.1481175 ,  0.75358377, -0.22679688, ...,  0.19296084,
         0.05335857,  0.42217209],
       [-0.61532326,  1.78003687, -0.16892195, ..., -0.11664898,
        -0.48188003, -1.5079529 ],
       [-0.96234178,  0.34727942,  0.93070164, ...,  0.99794636,
         1.59216954, -0.92052356]], shape=(5181, 9))

In [23]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS

lr = LogisticRegression()

sel = EFS(lr, max_features=9, scoring='accuracy', cv=5)

In [24]:
model = sel.fit(X_train, y_train)

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(

In [25]:
model.best_score_

np.float64(0.5321379238447705)

In [26]:
model.best_feature_names_

('0', '1', '2', '3', '4', '5', '6', '7', '8')

In [27]:
model.subsets_

{0: {'feature_idx': (0,),
  'cv_scores': array([0.43972999, 0.44401544, 0.44305019, 0.43918919, 0.43918919]),
  'avg_score': np.float64(0.4410348011601628),
  'feature_names': ('0',)},
 1: {'feature_idx': (1,),
  'cv_scores': array([0.43876567, 0.44208494, 0.43918919, 0.43822394, 0.43918919]),
  'avg_score': np.float64(0.43949058577795314),
  'feature_names': ('1',)},
 2: {'feature_idx': (2,),
  'cv_scores': array([0.45708775, 0.44401544, 0.44401544, 0.45366795, 0.45945946]),
  'avg_score': np.float64(0.4516492108584684),
  'feature_names': ('2',)},
 3: {'feature_idx': (3,),
  'cv_scores': array([0.43972999, 0.44015444, 0.43918919, 0.43918919, 0.43918919]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('3',)},
 4: {'feature_idx': (4,),
  'cv_scores': array([0.43972999, 0.43918919, 0.44015444, 0.43822394, 0.44015444]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('4',)},
 5: {'feature_idx': (5,),
  'cv_scores': array([0.45515911, 0.44015444, 0.45656371, 0.45366795, 0.46138996]),
  'avg_score': np.float64(0.453387034920304),
  'feature_names': ('5',)},
 6: {'feature_idx': (6,),
  'cv_scores': array([0.43972999, 0.44015444, 0.43918919, 0.43918919, 0.43918919]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('6',)},
 7: {'feature_idx': (7,),
  'cv_scores': array([0.43972999, 0.44015444, 0.43918919, 0.43918919, 0.43918919]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('7',)},
 8: {'feature_idx': (8,),
  'cv_scores': array([0.50916104, 0.51254826, 0.51930502, 0.51833977, 0.50482625]),
  'avg_score': np.float64(0.5128360692970143),
  'feature_names': ('8',)},
 9: {'feature_idx': (0, 1),
  'cv_scores': array([0.43587271, 0.44305019, 0.44401544, 0.44015444, 0.43339768]),
  'avg_score': np.float64(0.43929809407147885),
  'feature_names': ('0', '1')},
 10: {'feature_idx': (0, 2),
  'cv_scores': array([0.45612343, 0.45656371, 0.4507722 , 0.45173745, 0.45752896]),
  'avg_score': np.float64(0.45454514991641315),
  'feature_names': ('0', '2')},
 11: {'feature_idx': (0, 3),
  'cv_scores': array([0.43972999, 0.44498069, 0.44111969, 0.44305019, 0.43725869]),
  'avg_score': np.float64(0.441227851353213),
  'feature_names': ('0', '3')},
 12: {'feature_idx': (0, 4),
  'cv_scores': array([0.43972999, 0.44594595, 0.45752896, 0.44498069, 0.45173745]),
  'avg_score': np.float64(0.44798460810996976),
  'feature_names': ('0', '4')},
 13: {'feature_idx': (0, 5),
  'cv_scores': array([0.46287367, 0.43725869, 0.46621622, 0.44787645, 0.47683398]),
  'avg_score': np.float64(0.45821180044902315),
  'feature_names': ('0', '5')},
 14: {'feature_idx': (0, 6),
  'cv_scores': array([0.43972999, 0.44498069, 0.44498069, 0.44498069, 0.44111969]),
  'avg_score': np.float64(0.44315835328371495),
  'feature_names': ('0', '6')},
 15: {'feature_idx': (0, 7),
  'cv_scores': array([0.43972999, 0.44980695, 0.44401544, 0.44015444, 0.44015444]),
  'avg_score': np.float64(0.44277225289761457),
  'feature_names': ('0', '7')},
 16: {'feature_idx': (0, 8),
  'cv_scores': array([0.52362584, 0.49227799, 0.50868726, 0.52702703, 0.49903475]),
  'avg_score': np.float64(0.5101305741614324),
  'feature_names': ('0', '8')},
 17: {'feature_idx': (1, 2),
  'cv_scores': array([0.45612343, 0.44498069, 0.4488417 , 0.45173745, 0.45752896]),
  'avg_score': np.float64(0.4518424472137105),
  'feature_names': ('1', '2')},
 18: {'feature_idx': (1, 3),
  'cv_scores': array([0.43876567, 0.44208494, 0.43822394, 0.42664093, 0.43532819]),
  'avg_score': np.float64(0.4362087324960999),
  'feature_names': ('1', '3')},
 19: {'feature_idx': (1, 4),
  'cv_scores': array([0.43972999, 0.43822394, 0.44015444, 0.43822394, 0.44015444]),
  'avg_score': np.float64(0.43929734942271104),
  'feature_names': ('1', '4')},
 20: {'feature_idx': (1, 5),
  'cv_scores': array([0.45901639, 0.45849421, 0.47393822, 0.46525097, 0.47683398]),
  'avg_score': np.float64(0.4667067535919995),
  'feature_names': ('1', '5')},
 21: {'feature_idx': (1, 6),
  'cv_scores': array([0.43876567, 0.44208494, 0.43918919, 0.43822394, 0.43918919]),
  'avg_score': np.float64(0.43949058577795314),
  'feature_names': ('1', '6')},
 22: {'feature_idx': (1, 7),
  'cv_scores': array([0.43876567, 0.43822394, 0.43918919, 0.43822394, 0.43918919]),
  'avg_score': np.float64(0.43871838500575244),
  'feature_names': ('1', '7')},
 23: {'feature_idx': (1, 8),
  'cv_scores': array([0.51783992, 0.51930502, 0.52799228, 0.52702703, 0.49227799]),
  'avg_score': np.float64(0.5168884478913408),
  'feature_names': ('1', '8')},
 24: {'feature_idx': (2, 3),
  'cv_scores': array([0.45708775, 0.44401544, 0.4469112 , 0.45173745, 0.45656371]),
  'avg_score': np.float64(0.45126311047236795),
  'feature_names': ('2', '3')},
 25: {'feature_idx': (2, 4),
  'cv_scores': array([0.46769527, 0.44980695, 0.44787645, 0.45366795, 0.46042471]),
  'avg_score': np.float64(0.4558942673214611),
  'feature_names': ('2', '4')},
 26: {'feature_idx': (2, 5),
  'cv_scores': array([0.47058824, 0.45656371, 0.46621622, 0.46718147, 0.47007722]),
  'avg_score': np.float64(0.46612536906654556),
  'feature_names': ('2', '5')},
 27: {'feature_idx': (2, 6),
  'cv_scores': array([0.45323047, 0.44498069, 0.4469112 , 0.45173745, 0.46138996]),
  'avg_score': np.float64(0.4516499555072361),
  'feature_names': ('2', '6')},
 28: {'feature_idx': (2, 7),
  'cv_scores': array([0.46673095, 0.47297297, 0.44980695, 0.46621622, 0.45849421]),
  'avg_score': np.float64(0.46284426043346005),
  'feature_names': ('2', '7')},
 29: {'feature_idx': (2, 8),
  'cv_scores': array([0.52555448, 0.51737452, 0.51833977, 0.52992278, 0.5019305 ]),
  'avg_score': np.float64(0.5186244103312571),
  'feature_names': ('2', '8')},
 30: {'feature_idx': (3, 4),
  'cv_scores': array([0.44551591, 0.43725869, 0.43918919, 0.43532819, 0.44787645]),
  'avg_score': np.float64(0.44103368418701105),
  'feature_names': ('3', '4')},
 31: {'feature_idx': (3, 5),
  'cv_scores': array([0.45998071, 0.4546332 , 0.46332046, 0.44787645, 0.45656371]),
  'avg_score': np.float64(0.4564749071981473),
  'feature_names': ('3', '5')},
 32: {'feature_idx': (3, 6),
  'cv_scores': array([0.43972999, 0.44015444, 0.43918919, 0.43918919, 0.43918919]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('3', '6')},
 33: {'feature_idx': (3, 7),
  'cv_scores': array([0.43972999, 0.44015444, 0.43918919, 0.43918919, 0.43918919]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('3', '7')},
 34: {'feature_idx': (3, 8),
  'cv_scores': array([0.52266152, 0.50965251, 0.51640927, 0.52220077, 0.48841699]),
  'avg_score': np.float64(0.511868212061076),
  'feature_names': ('3', '8')},
 35: {'feature_idx': (4, 5),
  'cv_scores': array([0.46190935, 0.43725869, 0.45559846, 0.45366795, 0.46911197]),
  'avg_score': np.float64(0.45550928390851253),
  'feature_names': ('4', '5')},
 36: {'feature_idx': (4, 6),
  'cv_scores': array([0.43972999, 0.43822394, 0.44015444, 0.43822394, 0.44015444]),
  'avg_score': np.float64(0.43929734942271104),
  'feature_names': ('4', '6')},
 37: {'feature_idx': (4, 7),
  'cv_scores': array([0.43972999, 0.43918919, 0.44015444, 0.43822394, 0.44015444]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('4', '7')},
 38: {'feature_idx': (4, 8),
  'cv_scores': array([0.51398264, 0.50482625, 0.52606178, 0.51833977, 0.496139  ]),
  'avg_score': np.float64(0.5118698875208036),
  'feature_names': ('4', '8')},
 39: {'feature_idx': (5, 6),
  'cv_scores': array([0.45708775, 0.43918919, 0.45366795, 0.4488417 , 0.46138996]),
  'avg_score': np.float64(0.45203531124456864),
  'feature_names': ('5', '6')},
 40: {'feature_idx': (5, 7),
  'cv_scores': array([0.487946  , 0.44980695, 0.46428571, 0.45656371, 0.48262548]),
  'avg_score': np.float64(0.46824557027064256),
  'feature_names': ('5', '7')},
 41: {'feature_idx': (5, 8),
  'cv_scores': array([0.50916104, 0.51254826, 0.52027027, 0.52316602, 0.496139  ]),
  'avg_score': np.float64(0.5122569187178637),
  'feature_names': ('5', '8')},
 42: {'feature_idx': (6, 7),
  'cv_scores': array([0.43972999, 0.44015444, 0.43918919, 0.43918919, 0.43918919]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('6', '7')},
 43: {'feature_idx': (6, 8),
  'cv_scores': array([0.51301832, 0.51158301, 0.52123552, 0.52799228, 0.50675676]),
  'avg_score': np.float64(0.5161171779300998),
  'feature_names': ('6', '8')},
 44: {'feature_idx': (7, 8),
  'cv_scores': array([0.50626808, 0.51544402, 0.52123552, 0.51833977, 0.49324324]),
  'avg_score': np.float64(0.5109061258530883),
  'feature_names': ('7', '8')},
 45: {'feature_idx': (0, 1, 2),
  'cv_scores': array([0.47155256, 0.44980695, 0.4507722 , 0.44980695, 0.44401544]),
  'avg_score': np.float64(0.4531908199699906),
  'feature_names': ('0', '1', '2')},
 46: {'feature_idx': (0, 1, 3),
  'cv_scores': array([0.44358727, 0.4488417 , 0.44498069, 0.43532819, 0.43339768]),
  'avg_score': np.float64(0.4412271067044452),
  'feature_names': ('0', '1', '3')},
 47: {'feature_idx': (0, 1, 4),
  'cv_scores': array([0.44069431, 0.44594595, 0.45656371, 0.44401544, 0.4527027 ]),
  'avg_score': np.float64(0.4479844219477778),
  'feature_names': ('0', '1', '4')},
 48: {'feature_idx': (0, 1, 5),
  'cv_scores': array([0.45998071, 0.45559846, 0.46332046, 0.45945946, 0.48359073]),
  'avg_score': np.float64(0.46438996511320524),
  'feature_names': ('0', '1', '5')},
 49: {'feature_idx': (0, 1, 6),
  'cv_scores': array([0.43587271, 0.4507722 , 0.4507722 , 0.44111969, 0.43339768]),
  'avg_score': np.float64(0.4423868971602819),
  'feature_names': ('0', '1', '6')},
 50: {'feature_idx': (0, 1, 7),
  'cv_scores': array([0.43587271, 0.44208494, 0.44305019, 0.43822394, 0.43725869]),
  'avg_score': np.float64(0.43929809407147885),
  'feature_names': ('0', '1', '7')},
 51: {'feature_idx': (0, 1, 8),
  'cv_scores': array([0.51591128, 0.51351351, 0.52123552, 0.53764479, 0.5       ]),
  'avg_score': np.float64(0.5176610209879255),
  'feature_names': ('0', '1', '8')},
 52: {'feature_idx': (0, 2, 3),
  'cv_scores': array([0.46576663, 0.46138996, 0.4507722 , 0.45559846, 0.44787645]),
  'avg_score': np.float64(0.4562807400319454),
  'feature_names': ('0', '2', '3')},
 53: {'feature_idx': (0, 2, 4),
  'cv_scores': array([0.48601736, 0.46621622, 0.46814672, 0.46235521, 0.47200772]),
  'avg_score': np.float64(0.47094864529772923),
  'feature_names': ('0', '2', '4')},
 54: {'feature_idx': (0, 2, 5),
  'cv_scores': array([0.46769527, 0.44015444, 0.47007722, 0.45849421, 0.47779923]),
  'avg_score': np.float64(0.4628440742712681),
  'feature_names': ('0', '2', '5')},
 55: {'feature_idx': (0, 2, 6),
  'cv_scores': array([0.46480231, 0.4546332 , 0.45366795, 0.4546332 , 0.4527027 ]),
  'avg_score': np.float64(0.4560878760010872),
  'feature_names': ('0', '2', '6')},
 56: {'feature_idx': (0, 2, 7),
  'cv_scores': array([0.47733848, 0.46621622, 0.45656371, 0.46428571, 0.46235521]),
  'avg_score': np.float64(0.46535186515900107),
  'feature_names': ('0', '2', '7')},
 57: {'feature_idx': (0, 2, 8),
  'cv_scores': array([0.5265188 , 0.5       , 0.51833977, 0.52702703, 0.50482625]),
  'avg_score': np.float64(0.5153423708872118),
  'feature_names': ('0', '2', '8')},
 58: {'feature_idx': (0, 3, 4),
  'cv_scores': array([0.45612343, 0.4527027 , 0.45945946, 0.44401544, 0.4469112 ]),
  'avg_score': np.float64(0.4518424472137105),
  'feature_names': ('0', '3', '4')},
 59: {'feature_idx': (0, 3, 5),
  'cv_scores': array([0.46673095, 0.43822394, 0.47200772, 0.44787645, 0.47586873]),
  'avg_score': np.float64(0.4601415577307574),
  'feature_names': ('0', '3', '5')},
 60: {'feature_idx': (0, 3, 6),
  'cv_scores': array([0.44069431, 0.44594595, 0.44498069, 0.44498069, 0.43532819]),
  'avg_score': np.float64(0.44238596634932215),
  'feature_names': ('0', '3', '6')},
 61: {'feature_idx': (0, 3, 7),
  'cv_scores': array([0.43972999, 0.4488417 , 0.44594595, 0.4469112 , 0.44305019]),
  'avg_score': np.float64(0.4448958050211666),
  'feature_names': ('0', '3', '7')},
 62: {'feature_idx': (0, 3, 8),
  'cv_scores': array([0.52844744, 0.503861  , 0.51737452, 0.52895753, 0.49420849]),
  'avg_score': np.float64(0.5145697977906271),
  'feature_names': ('0', '3', '8')},
 63: {'feature_idx': (0, 4, 5),
  'cv_scores': array([0.47540984, 0.42857143, 0.45173745, 0.44594595, 0.46911197]),
  'avg_score': np.float64(0.4541553262864738),
  'feature_names': ('0', '4', '5')},
 64: {'feature_idx': (0, 4, 6),
  'cv_scores': array([0.44455159, 0.45173745, 0.45559846, 0.44787645, 0.45173745]),
  'avg_score': np.float64(0.45030027961561225),
  'feature_names': ('0', '4', '6')},
 65: {'feature_idx': (0, 4, 7),
  'cv_scores': array([0.43972999, 0.44594595, 0.45849421, 0.44498069, 0.45173745]),
  'avg_score': np.float64(0.4481776583030199),
  'feature_names': ('0', '4', '7')},
 66: {'feature_idx': (0, 4, 8),
  'cv_scores': array([0.51976856, 0.49903475, 0.50868726, 0.52992278, 0.49517375]),
  'avg_score': np.float64(0.5105174191963006),
  'feature_names': ('0', '4', '8')},
 67: {'feature_idx': (0, 5, 6),
  'cv_scores': array([0.47155256, 0.43436293, 0.47297297, 0.44594595, 0.48552124]),
  'avg_score': np.float64(0.46207112885029955),
  'feature_names': ('0', '5', '6')},
 68: {'feature_idx': (0, 5, 7),
  'cv_scores': array([0.487946  , 0.44401544, 0.47393822, 0.46235521, 0.48938224]),
  'avg_score': np.float64(0.4715274235524959),
  'feature_names': ('0', '5', '7')},
 69: {'feature_idx': (0, 5, 8),
  'cv_scores': array([0.52362584, 0.496139  , 0.50675676, 0.52992278, 0.49324324]),
  'avg_score': np.float64(0.5099375239683822),
  'feature_names': ('0', '5', '8')},
 70: {'feature_idx': (0, 6, 7),
  'cv_scores': array([0.43972999, 0.44787645, 0.44401544, 0.44594595, 0.44305019]),
  'avg_score': np.float64(0.4441236042489659),
  'feature_names': ('0', '6', '7')},
 71: {'feature_idx': (0, 6, 8),
  'cv_scores': array([0.52073288, 0.50289575, 0.51061776, 0.53185328, 0.49903475]),
  'avg_score': np.float64(0.5130268855437612),
  'feature_names': ('0', '6', '8')},
 72: {'feature_idx': (0, 7, 8),
  'cv_scores': array([0.50916104, 0.50675676, 0.51158301, 0.52413127, 0.50482625]),
  'avg_score': np.float64(0.5112916677526128),
  'feature_names': ('0', '7', '8')},
 73: {'feature_idx': (1, 2, 3),
  'cv_scores': array([0.45901639, 0.4488417 , 0.4507722 , 0.4469112 , 0.45559846]),
  'avg_score': np.float64(0.45222798911323503),
  'feature_names': ('1', '2', '3')},
 74: {'feature_idx': (1, 2, 4),
  'cv_scores': array([0.46287367, 0.44305019, 0.4527027 , 0.4507722 , 0.45945946]),
  'avg_score': np.float64(0.45377164600886877),
  'feature_names': ('1', '2', '4')},
 75: {'feature_idx': (1, 2, 5),
  'cv_scores': array([0.45515911, 0.45752896, 0.47683398, 0.45945946, 0.47683398]),
  'avg_score': np.float64(0.46516309669636574),
  'feature_names': ('1', '2', '5')},
 76: {'feature_idx': (1, 2, 6),
  'cv_scores': array([0.45805207, 0.4469112 , 0.44787645, 0.4507722 , 0.45656371]),
  'avg_score': np.float64(0.45203512508237675),
  'feature_names': ('1', '2', '6')},
 77: {'feature_idx': (1, 2, 7),
  'cv_scores': array([0.46769527, 0.4546332 , 0.4546332 , 0.45559846, 0.4546332 ]),
  'avg_score': np.float64(0.45743866886586265),
  'feature_names': ('1', '2', '7')},
 78: {'feature_idx': (1, 2, 8),
  'cv_scores': array([0.52266152, 0.52027027, 0.52123552, 0.53088803, 0.49034749]),
  'avg_score': np.float64(0.5170805672734313),
  'feature_names': ('1', '2', '8')},
 79: {'feature_idx': (1, 3, 4),
  'cv_scores': array([0.44744455, 0.43339768, 0.44305019, 0.42277992, 0.4469112 ]),
  'avg_score': np.float64(0.4387167095460248),
  'feature_names': ('1', '3', '4')},
 80: {'feature_idx': (1, 3, 5),
  'cv_scores': array([0.46769527, 0.46138996, 0.47779923, 0.46718147, 0.47007722]),
  'avg_score': np.float64(0.4688286302558241),
  'feature_names': ('1', '3', '5')},
 81: {'feature_idx': (1, 3, 6),
  'cv_scores': array([0.43876567, 0.44208494, 0.43918919, 0.42664093, 0.43436293]),
  'avg_score': np.float64(0.4362087324960999),
  'feature_names': ('1', '3', '6')},
 82: {'feature_idx': (1, 3, 7),
  'cv_scores': array([0.43876567, 0.44305019, 0.43532819, 0.42664093, 0.43339768]),
  'avg_score': np.float64(0.4354365317238991),
  'feature_names': ('1', '3', '7')},
 83: {'feature_idx': (1, 3, 8),
  'cv_scores': array([0.51976856, 0.52316602, 0.52799228, 0.51640927, 0.49131274]),
  'avg_score': np.float64(0.5157297744086558),
  'feature_names': ('1', '3', '8')},
 84: {'feature_idx': (1, 4, 5),
  'cv_scores': array([0.47155256, 0.45849421, 0.49324324, 0.47393822, 0.46911197]),
  'avg_score': np.float64(0.47326804004721074),
  'feature_names': ('1', '4', '5')},
 85: {'feature_idx': (1, 4, 6),
  'cv_scores': array([0.43972999, 0.43725869, 0.44015444, 0.43822394, 0.44015444]),
  'avg_score': np.float64(0.4391042992296609),
  'feature_names': ('1', '4', '6')},
 86: {'feature_idx': (1, 4, 7),
  'cv_scores': array([0.43972999, 0.43918919, 0.44015444, 0.43822394, 0.44015444]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('1', '4', '7')},
 87: {'feature_idx': (1, 4, 8),
  'cv_scores': array([0.51591128, 0.51833977, 0.52702703, 0.52702703, 0.49227799]),
  'avg_score': np.float64(0.516116619443524),
  'feature_names': ('1', '4', '8')},
 88: {'feature_idx': (1, 5, 6),
  'cv_scores': array([0.46673095, 0.46814672, 0.47104247, 0.47683398, 0.48166023]),
  'avg_score': np.float64(0.4728828704720701),
  'feature_names': ('1', '5', '6')},
 89: {'feature_idx': (1, 5, 7),
  'cv_scores': array([0.48601736, 0.46911197, 0.49517375, 0.48359073, 0.49517375]),
  'avg_score': np.float64(0.48581351016259405),
  'feature_names': ('1', '5', '7')},
 90: {'feature_idx': (1, 5, 8),
  'cv_scores': array([0.50916104, 0.51833977, 0.52702703, 0.51833977, 0.49324324]),
  'avg_score': np.float64(0.5132221696831147),
  'feature_names': ('1', '5', '8')},
 91: {'feature_idx': (1, 6, 7),
  'cv_scores': array([0.43876567, 0.43822394, 0.43918919, 0.43822394, 0.43918919]),
  'avg_score': np.float64(0.43871838500575244),
  'feature_names': ('1', '6', '7')},
 92: {'feature_idx': (1, 6, 8),
  'cv_scores': array([0.51783992, 0.52123552, 0.52992278, 0.52413127, 0.49710425]),
  'avg_score': np.float64(0.518046749049642),
  'feature_names': ('1', '6', '8')},
 93: {'feature_idx': (1, 7, 8),
  'cv_scores': array([0.51494696, 0.52606178, 0.52606178, 0.53088803, 0.49227799]),
  'avg_score': np.float64(0.5180473075362179),
  'feature_names': ('1', '7', '8')},
 94: {'feature_idx': (2, 3, 4),
  'cv_scores': array([0.46962392, 0.46138996, 0.46718147, 0.43629344, 0.44980695]),
  'avg_score': np.float64(0.45685914596232824),
  'feature_names': ('2', '3', '4')},
 95: {'feature_idx': (2, 3, 5),
  'cv_scores': array([0.47058824, 0.45752896, 0.47007722, 0.4546332 , 0.47200772]),
  'avg_score': np.float64(0.4649670679082444),
  'feature_names': ('2', '3', '5')},
 96: {'feature_idx': (2, 3, 6),
  'cv_scores': array([0.45515911, 0.44305019, 0.44594595, 0.45173745, 0.46235521]),
  'avg_score': np.float64(0.45164958318285225),
  'feature_names': ('2', '3', '6')},
 97: {'feature_idx': (2, 3, 7),
  'cv_scores': array([0.46769527, 0.47200772, 0.4488417 , 0.46621622, 0.45173745]),
  'avg_score': np.float64(0.46129967272686656),
  'feature_names': ('2', '3', '7')},
 98: {'feature_idx': (2, 3, 8),
  'cv_scores': array([0.52941176, 0.51351351, 0.51833977, 0.52413127, 0.49034749]),
  'avg_score': np.float64(0.5151487622075858),
  'feature_names': ('2', '3', '8')},
 99: {'feature_idx': (2, 4, 5),
  'cv_scores': array([0.46576663, 0.44787645, 0.46138996, 0.45366795, 0.48069498]),
  'avg_score': np.float64(0.46187919563040103),
  'feature_names': ('2', '4', '5')},
 100: {'feature_idx': (2, 4, 6),
  'cv_scores': array([0.46287367, 0.4488417 , 0.4469112 , 0.46042471, 0.45849421]),
  'avg_score': np.float64(0.45550909774632053),
  'feature_names': ('2', '4', '6')},
 101: {'feature_idx': (2, 4, 7),
  'cv_scores': array([0.47155256, 0.45945946, 0.45173745, 0.47297297, 0.45752896]),
  'avg_score': np.float64(0.46265027942945014),

In [28]:
metric_df = pd.DataFrame.from_dict(model.get_metric_dict()).T

In [29]:
metric_df

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
0,"(0,)","[0.43972999035679844, 0.444015444015444, 0.443...",0.441035,"(0,)",0.002663,0.002072,0.001036
1,"(1,)","[0.43876567020250723, 0.4420849420849421, 0.43...",0.439491,"(1,)",0.001728,0.001345,0.000672
2,"(2,)","[0.4570877531340405, 0.444015444015444, 0.4440...",0.451649,"(2,)",0.008353,0.006499,0.00325
3,"(3,)","[0.43972999035679844, 0.44015444015444016, 0.4...",0.43949,"(3,)",0.000505,0.000393,0.000196
4,"(4,)","[0.43972999035679844, 0.4391891891891892, 0.44...",0.43949,"(4,)",0.000933,0.000726,0.000363
...,...,...,...,...,...,...,...
506,"(0, 1, 2, 4, 5, 6, 7, 8)","[0.5207328833172613, 0.5144787644787645, 0.534...",0.524224,"(0, 1, 2, 4, 5, 6, 7, 8)",0.009257,0.007202,0.003601
507,"(0, 1, 3, 4, 5, 6, 7, 8)","[0.5265188042430087, 0.5222007722007722, 0.538...",0.528856,"(0, 1, 3, 4, 5, 6, 7, 8)",0.007025,0.005466,0.002733
508,"(0, 2, 3, 4, 5, 6, 7, 8)","[0.5390549662487946, 0.5144787644787645, 0.516...",0.524799,"(0, 2, 3, 4, 5, 6, 7, 8)",0.012011,0.009345,0.004672
509,"(1, 2, 3, 4, 5, 6, 7, 8)","[0.5226615236258437, 0.527027027027027, 0.5347...",0.526154,"(1, 2, 3, 4, 5, 6, 7, 8)",0.011102,0.008637,0.004319
510,"(0, 1, 2, 3, 4, 5, 6, 7, 8)","[0.5255544840887174, 0.5328185328185329, 0.539...",0.532138,"(0, 1, 2, 3, 4, 5, 6, 7, 8)",0.006082,0.004732,0.002366

In [68]:
X_train_sel = sel.transform(X_train)
X_test_sel = sel.transform(X_test)

In [69]:
X_train_sel

array([[ 0.21752121,  0.24035722, -0.77660867, ...,  0.44064869,
        -0.61568968,  1.68094926],
       [ 0.28692491, -0.76471144, -0.63192136, ...,  1.24563422,
         1.05693094,  0.42217209],
       [ 1.81380643, -0.27286933,  1.04645149, ...,  0.44064869,
         3.06407569,  1.26135687],
       ...,
       [ 0.1481175 ,  0.75358377, -0.22679688, ...,  0.19296084,
         0.05335857,  0.42217209],
       [-0.61532326,  1.78003687, -0.16892195, ..., -0.11664898,
        -0.48188003, -1.5079529 ],
       [-0.96234178,  0.34727942,  0.93070164, ...,  0.99794636,
         1.59216954, -0.92052356]], shape=(5181, 9))

In [55]:
model = LogisticRegression()

print("training",np.mean(cross_val_score(model, X_train_sel, y_train, cv=5, scoring='accuracy')))
print("testing",np.mean(cross_val_score(model, X_test_sel, y_test, cv=5, scoring='accuracy')))

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training 0.5321379238447705
testing 0.516991386991387

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

### Sequential Backward Elimination

In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

# load the dataset
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv')

df.drop(columns=['type','fixed acidity','volatile acidity'],inplace=True)

df.dropna(inplace=True)

# separate the target variable
X = df.drop("quality", axis=1)
y = df['quality']


# split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train.shape)

(5181, 9)

In [57]:
sfs = SFS(lr, k_features='best', forward=False, floating=False, scoring='r2',cv=5)

sfs.fit(X_train, y_train)

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(

SequentialFeatureSelector(estimator=LogisticRegression(), forward=False,
                          k_features=(1, 9), scoring='r2')

In [58]:
sfs.k_feature_idx_

(0, 1, 3, 4, 5, 6, 7, 8)

In [59]:
metric_df = pd.DataFrame.from_dict(sfs.get_metric_dict()).T

In [60]:
metric_df

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
9,"(0, 1, 2, 3, 4, 5, 6, 7, 8)","[0.06743685263479493, 0.11482192109365619, 0.1...",0.104678,"(0, 1, 2, 3, 4, 5, 6, 7, 8)",0.027204,0.021166,0.010583
8,"(0, 1, 3, 4, 5, 6, 7, 8)","[0.08659910908750468, 0.09670424111604092, 0.1...",0.108712,"(0, 1, 3, 4, 5, 6, 7, 8)",0.028245,0.021975,0.010988
7,"(0, 1, 3, 4, 5, 7, 8)","[0.06743685263479493, 0.0876454011272334, 0.14...",0.098737,"(0, 1, 3, 4, 5, 7, 8)",0.032675,0.025422,0.012711
6,"(1, 3, 4, 5, 7, 8)","[0.058494466290197056, 0.11352780109525507, 0....",0.087075,"(1, 3, 4, 5, 7, 8)",0.028954,0.022527,0.011264
5,"(1, 3, 4, 7, 8)","[0.05593949876316906, 0.1018807211096453, 0.12...",0.083475,"(1, 3, 4, 7, 8)",0.042913,0.033388,0.016694
4,"(1, 3, 7, 8)","[0.04827459618208518, 0.11482192109365619, 0.1...",0.084531,"(1, 3, 7, 8)",0.049285,0.038345,0.019173
3,"(3, 7, 8)","[0.05593949876316906, 0.0811748011352279, 0.10...",0.077799,"(3, 7, 8)",0.028278,0.022001,0.011
2,"(3, 8)","[0.053384531236141175, 0.04882180117520074, 0....",0.055008,"(3, 8)",0.026851,0.020891,0.010445
1,"(8,)","[0.02272492091180567, 0.059174761162409384, 0....",0.054009,"(8,)",0.032665,0.025415,0.012707

In [61]:
X_train_sel = sfs.transform(X_train)
X_test_sel = sfs.transform(X_test)

model = LogisticRegression()

print("training",np.mean(cross_val_score(model, X_train_sel, y_train, cv=5, scoring='accuracy')))
print("testing",np.mean(cross_val_score(model, X_test_sel, y_test, cv=5, scoring='accuracy')))

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(

training 0.5288558844007252
testing 0.5177517077517078

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

# Forward Selection

In [62]:
sfs = SFS(lr, k_features='best', forward=True, floating=False, scoring='r2',cv=5)

sfs.fit(X_train, y_train)

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

SequentialFeatureSelector(estimator=LogisticRegression(), k_features=(1, 9),
                          scoring='r2')

In [63]:
sfs.k_feature_idx_

(0, 1, 2, 3, 4, 5, 6, 7, 8)

In [64]:
metric_df = pd.DataFrame.from_dict(sfs.get_metric_dict()).T

In [65]:
metric_df

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(8,)","[0.02272492091180567, 0.059174761162409384, 0....",0.054009,"(8,)",0.032665,0.025415,0.012707
2,"(2, 8)","[0.059771950053711054, 0.07729244114002465, 0....",0.074208,"(2, 8)",0.037075,0.028845,0.014423
3,"(2, 7, 8)","[0.046997112418571296, 0.09023364112403554, 0....",0.07731,"(2, 7, 8)",0.036738,0.028583,0.014292
4,"(1, 2, 7, 8)","[0.05210704747262718, 0.12129252108566169, 0.0...",0.088105,"(1, 2, 7, 8)",0.039709,0.030895,0.015448
5,"(1, 2, 6, 7, 8)","[0.053384531236141175, 0.11741016109045832, 0....",0.091663,"(1, 2, 6, 7, 8)",0.044409,0.034552,0.017276
6,"(0, 1, 2, 6, 7, 8)","[0.06999182016182293, 0.09799836111444205, 0.1...",0.096709,"(0, 1, 2, 6, 7, 8)",0.040078,0.031182,0.015591
7,"(0, 1, 2, 5, 6, 7, 8)","[0.05593949876316906, 0.09929248111284317, 0.1...",0.097486,"(0, 1, 2, 5, 6, 7, 8)",0.036383,0.028307,0.014154
8,"(0, 1, 2, 4, 5, 6, 7, 8)","[0.059771950053711054, 0.08893952112563441, 0....",0.096174,"(0, 1, 2, 4, 5, 6, 7, 8)",0.029596,0.023027,0.011514
9,"(0, 1, 2, 3, 4, 5, 6, 7, 8)","[0.06743685263479493, 0.11482192109365619, 0.1...",0.104678,"(0, 1, 2, 3, 4, 5, 6, 7, 8)",0.027204,0.021166,0.010583

In [67]:
X_train_sel = sfs.transform(X_train)
X_test_sel = sfs.transform(X_test)

model = LogisticRegression()

print("training",np.mean(cross_val_score(model, X_train_sel, y_train, cv=5, scoring='accuracy')))
print("testing",np.mean(cross_val_score(model, X_test_sel, y_test, cv=5, scoring='accuracy')))

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training 0.5321379238447705
testing 0.516991386991387

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

## Using sklearn

In [83]:
from sklearn.feature_selection import SequentialFeatureSelector as SFS


sfs2 = SFS(model,
           n_features_to_select=5,
           direction='forward',
           scoring='r2',
           n_jobs=-1,
           cv=5)

sfs2 = sfs2.fit(X_train, y_train)

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(

In [88]:
np.arange(X_train.shape[1])[sfs2.support_]

array([0, 3, 6, 7, 8])

# Recursive Feature Selection

In [72]:
df = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [73]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [74]:
X.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [75]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X,y)

RandomForestClassifier()

In [76]:
rf.feature_importances_

array([0.11423898, 0.02200886, 0.42727825, 0.4364739 ])

In [77]:
X.drop(columns='sepal_width',inplace=True)
X.head()

   sepal_length  petal_length  petal_width
0           5.1           1.4          0.2
1           4.9           1.4          0.2
2           4.7           1.3          0.2
3           4.6           1.5          0.2
4           5.0           1.4          0.2

In [78]:
rf = RandomForestClassifier()
rf.fit(X,y)

rf.feature_importances_

array([0.17154561, 0.44010048, 0.38835392])

In [79]:
X.drop(columns='sepal_length',inplace=True)
X.head()

   petal_length  petal_width
0           1.4          0.2
1           1.4          0.2
2           1.3          0.2
3           1.5          0.2
4           1.4          0.2

In [80]:
rf = RandomForestClassifier()
rf.fit(X,y)

rf.feature_importances_

array([0.53175704, 0.46824296])

In [81]:
X.drop(columns='petal_length',inplace=True)
X.head()

   petal_width
0          0.2
1          0.2
2          0.2
3          0.2
4          0.2

### Using Sklearn RFE

In [82]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Load iris dataset
url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
df = pd.read_csv(url)

# Separate features and target variable
X = df.drop("species", axis=1)
y = df["species"]

# Initialize RandomForestClassifier
model = RandomForestClassifier()

# Initialize RFE
rfe = RFE(estimator=model, n_features_to_select=1)

# Fit RFE
rfe.fit(X, y)

# Print the ranking
ranking = rfe.ranking_
print("Feature ranking:")

for i, feature in enumerate(X.columns):
    print(f"{feature}: {ranking[i]}")

Feature ranking:
sepal_length: 3
sepal_width: 4
petal_length: 2
petal_width: 1

In [89]:
rfe.support_

array([False, False, False,  True])

In [90]:
X.columns[rfe.support_]

Index(['petal_width'], dtype='str')

### RFECV

In [91]:
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

selector = RFECV(
    estimator=model,
    step=1,
    cv=5,
    scoring='accuracy'
)

selector.fit(X, y)

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

RFECV(cv=5, estimator=LogisticRegression(), scoring='accuracy')

In [92]:
selector.n_features_

np.int64(4)

In [93]:
X.columns[selector.support_]

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='str')