In [60]:
import pandas as pd 
import numpy as np

In [61]:
df = pd.read_csv('used_car_listings.csv')

In [62]:
df.head()

,listing_id,vin,make,model,year,trim,body_type,fuel_type,transmission,mileage,price,condition,location,seller_type,features
0,1,9M6LF68V634LY2252,Tesla,Model 3,2019,NaN,Coupe,Electric,Manual,46134,19919.0,good,"New Lindsey, GA, US",Dealer,"Alloy Wheels, Android Auto, Apple CarPlay, Fog..."
1,2,1S0ZCY536BSCY2864,Nissan,Rogue,2024,LT,Sedan,Hybrid,Automatic,16109,19480.0,good,"Pughtown, CO, US",Dealer,"Alloy Wheels, Android Auto, Lane Keep Assist, ..."
2,3,YFB625BN0RTMZ5590,Hyundai,i20,2018,XLE,Crossover,Petrol,Automatic,173239,4556.0,good,"Satna, HR, India",Dealer,"Alloy Wheels, Bluetooth, Panoramic Roof, Sunroof"
3,4,CPMZ4RFN5WYL37096,Kia,Sportage,2023,EX,Hatchback,Diesel,CVT,36810,11536.0,fair,"山武市, Osaka, Japan",Certified Pre-Owned,"Alloy Wheels, Bluetooth, Keyless Entry, Naviga..."
4,5,4PJZG3MV6D9365673,Kia,Seltos,2020,Trend,Pickup,Diesel,Automatic,87749,14098.0,good,"長生郡長生村, Osaka, Japan",Certified Pre-Owned,"Apple CarPlay, Backup Camera, Bluetooth, Heate..."

In [63]:
df = df[['make','model','body_type','fuel_type','transmission','mileage','price','condition','seller_type']]

In [64]:
df.head()

,make,model,body_type,fuel_type,transmission,mileage,price,condition,seller_type
0,Tesla,Model 3,Coupe,Electric,Manual,46134,19919.0,good,Dealer
1,Nissan,Rogue,Sedan,Hybrid,Automatic,16109,19480.0,good,Dealer
2,Hyundai,i20,Crossover,Petrol,Automatic,173239,4556.0,good,Dealer
3,Kia,Sportage,Hatchback,Diesel,CVT,36810,11536.0,fair,Certified Pre-Owned
4,Kia,Seltos,Pickup,Diesel,Automatic,87749,14098.0,good,Certified Pre-Owned

In [65]:

df['transmission'].value_counts()

transmission
Automatic    1109
Manual        635
CVT           214
DCT            61
AMT            49
Name: count, dtype: int64

# 
Train test split

In [79]:
x = df[['make','model','body_type','fuel_type','transmission','mileage','price','condition','seller_type']]

In [80]:
y = df['price']

In [81]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2,random_state=0)

In [69]:
x_train.shape,x_test.shape

((1654, 8), (414, 8))

# One Hot Encoding

In [70]:
counts = df['model'].value_counts()

In [71]:
df['model'].value_counts()
threshold=40
repl = counts[counts<=threshold].index
#pd.get_dummies(x_train['model'].replace(repl,'uncommon'))

In [72]:

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

x_train_new = ohe.fit_transform(x_train[['make','body_type','fuel_type','transmission','seller_type','model']].replace(repl,'uncommon'))
x_test_new = ohe.transform(x_test[['make','body_type','fuel_type','transmission','seller_type','model']].replace(repl,'uncommon'))

In [73]:
x_train_new.shape

(1654, 48)

In [84]:
np.hstack((x_train[['mileage','condition']].values,x_train_new))
#np.hstack((x_train[['mileage','condition']].values,x_train_new)).shape

(1654, 50)

In [86]:
np.hstack((x_test[['mileage','condition']].values,x_test_new))
#np.hstack((x_test[['mileage','condition']].values,x_test_new)).shape

(414, 50)