In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV

In [2]:
df = pd.read_csv("Salary_dataset (1).csv")

In [4]:
df.head()

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [7]:
df = df.drop(columns=['Unnamed: 0'])

In [8]:
df.head()

   YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [9]:
df.shape

(30, 2)

In [21]:
X = df[['Salary']]
y = df.iloc[:,1]

In [22]:
X.head()

    Salary
0  39344.0
1  46206.0
2  37732.0
3  43526.0
4  39892.0

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [24]:
drt = DecisionTreeRegressor(criterion = 'friedman_mse', max_depth=5)

In [25]:
drt.fit(X_train,y_train)

DecisionTreeRegressor(criterion='friedman_mse', max_depth=5)

In [26]:
y_pred = drt.predict(X_test)

In [27]:
r2_score(y_test,y_pred)

0.9907186946388579

# Hyperparameter Tuning

In [29]:
param_grid = {
    'max_depth':[2,4,8,10,None],
    'max_features':[0.25,0.5,1.0],
    'min_samples_split':[0.25,0.5,1.0]
}

In [30]:
reg = GridSearchCV(DecisionTreeRegressor(),param_grid=param_grid)

In [31]:
reg.fit(X_train,y_train)

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'max_depth': [2, 4, 8, 10, None],
                         'max_features': [0.25, 0.5, 1.0],
                         'min_samples_split': [0.25, 0.5, 1.0]})

In [32]:
reg.best_score_

np.float64(0.9379757813092967)

In [33]:
reg.best_params_

{'max_depth': 4, 'max_features': 0.25, 'min_samples_split': 0.25}