In [32]:
import numpy as np
import pandas as pd

In [33]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [34]:
df = pd.read_csv('train.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [35]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [36]:
df['Family'] = df['SibSp'] + df['Parch']

In [37]:
df.head()

    Age     Fare  SibSp  Parch  Survived  Family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [38]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [39]:
df.head()

    Age     Fare  Survived  Family
0  22.0   7.2500         0       1
1  38.0  71.2833         1       1
2  26.0   7.9250         1       0
3  35.0  53.1000         1       1
4  35.0   8.0500         0       0

In [40]:
x = df.drop(columns='Survived')
y = df['Survived']

In [41]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x_train.head()

      Age     Fare  Family
331  45.5  28.5000       0
733  23.0  13.0000       0
382  32.0   7.9250       0
704  26.0   7.8542       1
813   6.0  31.2750       6

In [42]:
# Without binarization

In [43]:
clf = DecisionTreeClassifier()

clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

accuracy_score(y_test, y_pred)

0.6424581005586593

In [44]:
np.mean(cross_val_score(clf,x,y,cv=10,scoring='accuracy'))

0.6453183520599252

In [45]:
# Applying Binarization

In [46]:
from sklearn.preprocessing import Binarizer

trf = ColumnTransformer([
    ('bin',Binarizer(copy=False, threshold=0),[2])
],remainder='passthrough')

x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

pd.DataFrame(x_train_trf,columns=['Age','Fare','Family']).head()

   Age  Fare   Family
0  0.0  45.5  28.5000
1  0.0  23.0  13.0000
2  0.0  32.0   7.9250
3  1.0  26.0   7.8542
4  1.0   6.0  31.2750

In [47]:
# with Binarization

In [48]:
clf = DecisionTreeClassifier()

clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

accuracy_score(y_test, y_pred)

0.6759776536312849

In [49]:
x_transformed = trf.transform(x)
np.mean(cross_val_score(clf,x_transformed,y,cv=10,scoring='accuracy'))

0.6554931335830212