In [76]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.impute import IterativeImputer,SimpleImputer

In [53]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [54]:
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [55]:
df.iloc[1,0] = np.NaN
df.iloc[3,1] = np.NaN
df.iloc[-1,-2] = np.NaN

In [56]:
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        NaN             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0             NaN             26.0    13.0
44        2.0            15.0              NaN     7.0

In [57]:
x = df.drop(columns='Profit')
y = df['Profit']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [58]:
x_train

    R&D Spend  Administration  Marketing Spend
44        2.0            15.0              NaN
2        15.0            10.0             41.0
21        8.0            15.0             30.0
14       12.0             NaN             26.0

In [77]:
si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)

x_test_trf2 = si.transform(x_test)

In [78]:
lr = LogisticRegression()

lr.fit(x_train_trf2,y_train)

y_pred2 = lr.predict(x_test_trf2)

accuracy_score(y_pred2,y_test)

E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.0

In [65]:
it = IterativeImputer(max_iter=10, random_state=0)

x_train_trf = it.fit_transform(x_train)

x_test_trf = it.transform(x_test)

In [73]:
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)

y_pred = lr.predict(x_test_trf)

accuracy_score(y_pred,y_test)

E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.0